# Specify a base image
FROM node:16-alpine

# Move to a folder to install and copy my files
WORKDIR '/app'

# Install some dependencies
COPY package.json .
RUN npm install
COPY . .

# Default command
CMD ["npm","run","start"]
